theme: jekyll-theme-cayman
title: Gemstone.Timeseries
description: GPA Gemstone Timeseries Library
github:
  repository_name: gemstone/timeseries
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
